### ISSUE TITLE
Cite your model

### ISSUE THREAD

**Issue by LiangZhang1996** [guang0123/PRGLight#1]
I would like to cite your article and add your model as a baseline. But I have some questions.

1. What's the cite format of your article? I can get your article from IJCAI-workshop, but cannot find the citation format with bibtex. could you provide it?

2. Is there any particular settings to run your model under other datasets?

**Comment by guang0123** [comment]
Thanks for your interest. 

For your first question, you may consider the following bibtex
```
@inproceedings{zhao2021prglight,
    title={{PRGLight}: {A} novel traffic light control framework with Pressure-based-Reinforcement Learning and Graph Neural Network},
    author={Zhao, Chenguang and  Hu, Xiaorong  and  Wang, Gang},
    booktitle={IJCAI 2021 Reinforcement Learning for Intelligent Transportation Systems (RL4ITS) Workshop},
    address={Virtual},
    month={Aug.},
    year={2021}
}
```

For your second question, if you would like to run with other data-sets, you can try other settings.

**Comment by LiangZhang1996** [comment]
Thank you!
