### ISSUE TITLE
What's the environment?

### ISSUE THREAD

**Issue by LiangZhang1996** [guang0123/PRGLight#2]
What's the exact version of Tensorflow and keras?
It's hard to run it without a proper environment.

**Comment by guang0123** [comment]
Thanks for your interest. We use tensorflow 1.11.0 and keras 2.1.0

**Comment by LiangZhang1996** [comment]
Thank you, I get it.

**Comment by twinklebee** [comment]
> Thank you, I get it.

Hello, Miss Zhang,

Via your index, I can't praise your work too much. I also have trouble in reproducing the code, could you give me some advice, thank you very much. And this is my own github ID.
