### ISSUE TITLE
Error occurs when predict time.

### ISSUE THREAD

**Issue by LiangZhang1996** [guang0123/PRGLight#3]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/43574084/170267457-32ffc802-f119-4661-aa3d-8e0262c8d1af.png">

**Comment by LiangZhang1996** [comment]
Some functions in gnnmodule.py cannot work.

**Comment by LiangZhang1996** [comment]
Is there any special configurations for JiNan and HangZhou datasets?

When running with light-dataset, all is right.
But when running with Jinan dataset, it occurs the error as above.

Could you give me some suggestions?

**Comment by LiangZhang1996** [comment]
It seems that the pre-trained GNN model has input shape of (None, 11, 1, 8), but under Jinan, the input shape is (None, 11, 12, 8).

How can I change it or re-train the GNN model?

**Comment by guang0123** [comment]
Thanks for your interest. The input shape of the GNN model varies among different the data-sets. In the Light data-set, there is only 1 intersection, so the input shape is (None, 11, 1, 8). For the Jinan and Hangzhou data-set, there are 12 and 16 intersections respectively, so the input shape is (None. 11, 12, 8) and (None, 11, 16, 8) respectively.

**Comment by guang0123** [comment]
To get the GNN model for other data-sets, re-training is necessary. In the paper we use the [Beijing data-set](https://github.com/p0llx/DeepST-ResNet/tree/master/data/TaxiBJ).

**Comment by LiangZhang1996** [comment]
Could you provide your pre-trained GNN models under JiNan, HangZhou, and New York?

**Comment by guang0123** [comment]
We have uploaded the pre-trained GNN model for Hangzhou, Jinan and Newyork.

**Comment by LiangZhang1996** [comment]
Thank you very much!
Best!
